spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 500MB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/poc/v1/
  port: 9999
